# Generated by Django 5.1.6 on 2025-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0002_preorder_product_delete_userdata_preorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к фото'),
        ),
    ]
