# Generated by Django 5.1.6 on 2025-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0003_product_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Пути к фото'),
        ),
    ]
