# Generated by Django 5.1.6 on 2025-03-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0004_product_composition_alter_product_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название напитка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
            },
        ),
    ]
